/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "addr.h"

bool_t
xdr_address (XDR *xdrs, address *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_short (xdrs, &objp->flag))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->addr_1))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->addr_2))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->addr_3))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->addr_4))
				 return FALSE;
		} else {
			IXDR_PUT_SHORT(buf, objp->flag);
			IXDR_PUT_U_LONG(buf, objp->addr_1);
			IXDR_PUT_U_LONG(buf, objp->addr_2);
			IXDR_PUT_U_LONG(buf, objp->addr_3);
			IXDR_PUT_U_LONG(buf, objp->addr_4);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_short (xdrs, &objp->flag))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->addr_1))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->addr_2))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->addr_3))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->addr_4))
				 return FALSE;
		} else {
			objp->flag = IXDR_GET_SHORT(buf);
			objp->addr_1 = IXDR_GET_U_LONG(buf);
			objp->addr_2 = IXDR_GET_U_LONG(buf);
			objp->addr_3 = IXDR_GET_U_LONG(buf);
			objp->addr_4 = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_short (xdrs, &objp->flag))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->addr_1))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->addr_2))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->addr_3))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->addr_4))
		 return FALSE;
	return TRUE;
}
