/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADDR_H_RPCGEN
#define _ADDR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct address {
	short flag;
	u_int addr_1;
	u_int addr_2;
	u_int addr_3;
	u_int addr_4;
};
typedef struct address address;

#define ADDRESSPROG 99
#define ADDRESSVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINTADDRESS 1
extern  int * printaddress_1(struct address *, CLIENT *);
extern  int * printaddress_1_svc(struct address *, struct svc_req *);
extern int addressprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINTADDRESS 1
extern  int * printaddress_1();
extern  int * printaddress_1_svc();
extern int addressprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_address (XDR *, address*);

#else /* K&R C */
extern bool_t xdr_address ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADDR_H_RPCGEN */
